# Generated by Django 4.2.5 on 2023-09-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_user_about_user_user_name_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
